// Generated by nuxt-simple-sitemap

import type { SitemapOutputHookCtx, SitemapRenderCtx, SitemapItemDefaults } from 'D:/Projects/website/node_modules/nuxt-simple-sitemap/dist/runtime/types'

declare module 'nitropack' {
  interface NitroRouteRules {
    index?: boolean
    sitemap?: SitemapItemDefaults
  }
  interface NitroRouteConfig {
    index?: boolean
    sitemap?: SitemapItemDefaults
  }
}
// extend nitro hooks
declare module 'nitropack/dist/runtime/types' {
  interface NitroRuntimeHooks {
    'sitemap:resolved': (ctx: SitemapRenderCtx) => void | Promise<void>
    'sitemap:output': (ctx: SitemapOutputHookCtx) => void | Promise<void>
  }
}

export {}
